package MySQLDatabase;

import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;

import com.dresslibrary.client.model.DressInfo;
import com.google.cloud.sql.jdbc.Connection;


public class DBConnection {
	java.sql.Connection myCon;
	Statement statment;
	
	
	public void connectToDB() throws ClassNotFoundException, SQLException{
		try{
			myCon = DriverManager.getConnection("jdbc:mysql://localhost:3306/dresslibrary", "root", "Forfattare1");
			statment = myCon.createStatement();
			
		}catch(Exception e){
			System.out.println("Error i con");
			e.printStackTrace();
		}
	}
	
	/*
	 *       try {
                PreparedStatement ps = myConnection.prepareStatement
                        ("INSERT INTO sorce (file,sorceName) VALUES(?,?)",
                                Statement.RETURN_GENERATED_KEYS);
                FileInputStream input = new FileInputStream(snippet.getFile());
                ps.setBinaryStream(1, input);
                ps.setString(2,snippet.getFileName());
                ps.executeUpdate();
                ResultSet tableKeys = ps.getGeneratedKeys();
                tableKeys.next();
                autoGeneratedID = tableKeys.getInt(1);
                snippet.setSorceID(autoGeneratedID);
            } catch (Exception e) {
                e.printStackTrace();
            }

	 */
	
	public void insertIntoDressInfo(DressInfo info){
		try{
			String sql = "INSERT INTO dressImages()";
			PreparedStatement ps = myCon.prepareStatement(sql);
		}catch(Exception e){
			e.printStackTrace();
		}
	}

}
